import {
  GrowthStage,
  CareType,
  NutrientType,
  StageGuide,
  EnvironmentTarget,
  NutrientSchedule,
} from '../types';

export const GROWTH_STAGES: GrowthStage[] = [
  'seed',
  'germination',
  'seedling',
  'vegetative',
  'pre-flower',
  'flowering',
  'late-flowering',
  'harvest',
  'drying',
  'curing',
  'complete',
];

export const STAGE_COLORS: Record<GrowthStage, string> = {
  seed: '#78716c',
  germination: '#a16207',
  seedling: '#65a30d',
  'pre-flower': '#16a34a',
  vegetative: '#15803d',
  flowering: '#9333ea',
  'late-flowering': '#7c3aed',
  harvest: '#dc2626',
  drying: '#d97706',
  curing: '#0891b2',
  complete: '#059669',
};

export const STAGE_ICONS: Record<GrowthStage, string> = {
  seed: 'seed-outline',
  germination: 'sprout-outline',
  seedling: 'leaf-outline',
  vegetative: 'tree-outline',
  'pre-flower': 'flower-outline',
  flowering: 'flower',
  'late-flowering': 'flower',
  harvest: 'cut-outline',
  drying: 'thermometer-outline',
  curing: 'flask-outline',
  complete: 'checkmark-circle-outline',
};

export const CARE_TYPES: { value: CareType; label: string; icon: string }[] = [
  { value: 'water', label: 'Water', icon: 'water-outline' },
  { value: 'nutrients', label: 'Nutrients', icon: 'flask-outline' },
  { value: 'ph_adjust', label: 'pH Adjust', icon: 'bandage-outline' },
  { value: 'prune', label: 'Prune', icon: 'cut-outline' },
  { value: 'top', label: 'Top', icon: 'resize-outline' },
  { value: 'lst', label: 'LST', icon: 'git-branch-outline' },
  { value: 'scrog', label: 'SCROG', icon: 'grid-outline' },
  { value: 'defoliate', label: 'Defoliate', icon: 'leaf-outline' },
  { value: 'flush', label: 'Flush', icon: 'water-outline' },
  { value: 'repot', label: 'Repot', icon: 'albums-outline' },
  { value: 'ipm', label: 'IPM', icon: 'bug-outline' },
  { value: 'other', label: 'Other', icon: 'ellipsis-horizontal-outline' },
];

export const NUTRIENT_TYPES: { value: NutrientType; label: string }[] = [
  { value: 'grow', label: 'Grow (Veg)' },
  { value: 'bloom', label: 'Bloom (Flower)' },
  { value: 'micro', label: 'Micro' },
  { value: 'calmag', label: 'Cal-Mag' },
  { value: 'boost', label: 'Bloom Booster' },
  { value: 'enzyme', label: 'Enzyme' },
  { value: 'silica', label: 'Silica' },
  { value: 'molasses', label: 'Molasses' },
  { value: 'custom', label: 'Custom' },
];

export const STAGE_GUIDES: StageGuide[] = [
  {
    stage: 'seed',
    name: 'Seed',
    duration: 'Day 0',
    description: 'The starting point. Store seeds in a cool, dark, dry place until ready to germinate.',
    keyTasks: [
      'Store seeds properly (cool, dark, dry)',
      'Decide on germination method',
      'Prepare growing medium',
      'Set up grow space',
    ],
    commonProblems: [
      'Poor seed quality',
      'Incorrect storage conditions',
      'Old non-viable seeds',
    ],
    tips: [
      'Use seeds from reputable breeders',
      'Refrigerate seeds for long-term storage',
      'Do not handle seeds with bare hands',
      'Perform a water test to check viability',
    ],
  },
  {
    stage: 'germination',
    name: 'Germination',
    duration: '1-7 days',
    description: 'The seed cracks open and the taproot emerges. Critical stage requiring warmth and moisture.',
    keyTasks: [
      'Soak seeds in water for 12-24 hours',
      'Transfer to paper towel method or directly to medium',
      'Maintain 75-80F (24-27C) temperature',
      'Keep high humidity (70-90%)',
      'Do not plant seed deeper than 0.5 inches',
    ],
    commonProblems: [
      'Seeds not cracking (too cold or old)',
      'Root rot from too much water',
      'Seed hull stuck on cotyledons',
    ],
    tips: [
      'Use distilled or pH balanced water',
      'Place in warm dark spot',
      'Check daily for taproot emergence',
      'Handle with extreme care once sprouted',
      'Plant taproot side down',
    ],
  },
  {
    stage: 'seedling',
    name: 'Seedling',
    duration: '1-3 weeks',
    description: 'Young plant with first true leaves. Very delicate - easy to overwater or over-fertilize.',
    keyTasks: [
      'Mist leaves or use humidity dome',
      'Water with plain pH water only',
      'Provide 18-24 hours of gentle light',
      'Keep humidity high (65-80%)',
      'Watch for overwatering signs',
      'No nutrients yet unless deficiency appears',
    ],
    commonProblems: [
      'Damping off (stem rot at soil line)',
      'Overwatering',
      'Light burn from too-intense lights',
      'Nutrient burn from feeding too early',
    ],
    tips: [
      'Use a spray bottle for watering',
      'Keep light 24+ inches away',
      'Use seedling mix or light soil',
      'Only water when top inch is dry',
      'Gentle air circulation strengthens stems',
    ],
  },
  {
    stage: 'vegetative',
    name: 'Vegetative',
    duration: '3-8 weeks',
    description: 'Rapid growth phase. Plant develops structure, branches, and foliage. Training techniques are applied here.',
    keyTasks: [
      'Begin nutrient regimen (grow formula)',
      'Water when top inch of soil is dry',
      'Apply training techniques (LST, topping, SCROG)',
      'Monitor plant height and width',
      'Defoliate as needed for airflow',
      'Maintain 18/6 or 20/4 light schedule',
      'Check pH and PPM regularly',
      'Repot if rootbound',
    ],
    commonProblems: [
      'Nutrient deficiencies (N, Mg, Ca)',
      'Stretching from insufficient light',
      'pH lockout',
      'Pest infestations',
      'Root rot from overwatering',
    ],
    tips: [
      'Start nutrients at 25-50% strength',
      'Increase nutrients gradually week by week',
      'Topping at 4th-5th node for bushier growth',
      'LST from week 2-3 for even canopy',
      'Keep temperature 70-85F, humidity 40-70%',
      'Flush every 2-3 weeks with plain water',
    ],
  },
  {
    stage: 'pre-flower',
    name: 'Pre-Flower',
    duration: '1-2 weeks',
    description: 'Transition period. Plant shows first signs of sex and flowering. Switch to 12/12 light for photoperiods.',
    keyTasks: [
      'Switch light to 12/12 (photoperiods)',
      'Identify plant gender (remove males)',
      'Begin transition to bloom nutrients',
      'Reduce nitrogen, increase phosphorus',
      'Scrog net installation if using SCROG',
      'Monitor for hermaphrodites',
    ],
    commonProblems: [
      'Hermaphrodite development from stress',
      'Light leaks causing reversion',
      'Early flower stretch',
    ],
    tips: [
      'Watch for white pistils at nodes',
      'Check under leaves for pre-flowers',
      'Reduce light stress during transition',
      'Start bloom nutrients at 50% strength',
    ],
  },
  {
    stage: 'flowering',
    name: 'Flowering',
    duration: '4-6 weeks',
    description: 'Buds are forming and swelling. Critical nutrition period. Focus on bloom nutrients and environment.',
    keyTasks: [
      'Full bloom nutrient regimen',
      'Monitor humidity (keep below 55%)',
      'Check trichomes weekly',
      'Defoliate for bud light exposure',
      'Monitor for mold and bud rot',
      'Adjust nutrients based on fade',
      'Record weekly growth snapshots',
    ],
    commonProblems: [
      'Powdery mildew from high humidity',
      'Bud rot (botrytis)',
      'Nutrient burn on leaf tips',
      'Spider mites',
      'Cal-Mag deficiencies',
    ],
    tips: [
      'Gradually reduce humidity as buds swell',
      'Maintain good airflow around buds',
      'Do not defoliate too aggressively',
      'Lower light intensity slightly in late flower',
      'Watch for amber trichomes developing',
    ],
  },
  {
    stage: 'late-flowering',
    name: 'Late Flower',
    duration: '2-4 weeks',
    description: 'Final weeks before harvest. Trichomes ripen, buds reach maximum density. Flush period.',
    keyTasks: [
      'Flush with plain pH water (1-2 weeks)',
      'Monitor trichome color closely',
      'Check pistil color changes',
      'Reduce nutrients gradually',
      'Maintain low humidity (40-50%)',
      'Final defoliation for air circulation',
      'Plan harvest timing',
    ],
    commonProblems: [
      'Bud rot from dense buds and humidity',
      'Harvesting too early',
      'Late pest infestations',
      'Foxtailing from heat stress',
    ],
    tips: [
      'Cloudy trichomes = energetic high',
      'Amber trichomes = more body/relaxing',
      'Harvest when 10-30% trichomes are amber for balanced effect',
      'Dark period before harvest can increase resin',
      'Check for mold inside dense buds',
    ],
  },
  {
    stage: 'harvest',
    name: 'Harvest',
    duration: '1 day',
    description: 'Cut, trim, and prepare buds for drying. Most rewarding day of the grow.',
    keyTasks: [
      'Cut whole plant or branch by branch',
      'Wet trim or dry trim (your choice)',
      'Remove large fan leaves',
      'Hang branches upside down to dry',
      'Record wet weight',
      'Prepare drying room conditions',
    ],
    commonProblems: [
      'Cutting too early',
      'Contamination from dirty tools',
      'Buds falling off during trim',
    ],
    tips: [
      'Use sharp, clean trimming scissors',
      'Keep trimmed sugar leaves for edibles/kief',
      'Maintain 60F/60% humidity in drying space',
      'Dry slowly over 7-14 days for best quality',
      'Jarring too early leads to mold',
    ],
  },
  {
    stage: 'drying',
    name: 'Drying',
    duration: '7-14 days',
    description: 'Slow drying is key to smooth smoke. Branch should snap, not bend, when ready.',
    keyTasks: [
      'Maintain 60F (15C) and 60% humidity',
      'Ensure good air circulation (not direct)',
      'Check branches daily for snap test',
      'Record dry weight when done',
      'Remove buds from stems when stems snap',
    ],
    commonProblems: [
      'Drying too fast (harsh smoke)',
      'Drying too slow (mold risk)',
      'Uneven drying from poor air flow',
      'Light exposure degrading quality',
    ],
    tips: [
      'Use a hygrometer in the drying space',
      'Trim smaller buds first (they dry faster)',
      'Brown paper bags work well for slowing dry',
      'Dark environment is best',
      '7-14 day dry is ideal range',
    ],
  },
  {
    stage: 'curing',
    name: 'Curing',
    duration: '2-8 weeks',
    description: 'Buds cure in airtight jars, burped daily. Develops flavor, smoothness, and potency.',
    keyTasks: [
      'Place trimmed buds in mason jars (75% full)',
      'Burp jars 2-3 times daily for first week',
      'Burp once daily for second week',
      'Burp every few days for remaining weeks',
      'Monitor humidity inside jars (62% ideal)',
      'Record cure weight and observations',
      'Final quality rating after curing',
    ],
    commonProblems: [
      'Mold from wet buds in jars',
      'Over-dried buds (too dry too fast)',
      'Ammonia smell from not burping enough',
    ],
    tips: [
      'Use Boveda packs to maintain 62% RH',
      'First week burping is critical',
      'Jars should smell good, not ammonia',
      '2-4 week minimum cure recommended',
      'Longer cures (2-3 months) produce best results',
      'Store in cool, dark place',
    ],
  },
  {
    stage: 'complete',
    name: 'Complete',
    duration: 'Done!',
    description: 'Grow cycle finished. Review your data and notes to improve the next run.',
    keyTasks: [
      'Record final harvest data',
      'Review all care logs and environment data',
      'Calculate total yield and potency',
      'Clean and sanitize grow space',
      'Plan next grow based on learnings',
    ],
    commonProblems: [],
    tips: [
      'Compare against previous grows',
      'Note which strains performed best',
      'Document environmental factors that worked',
      'Save clones or seeds for next run',
    ],
  },
];

export const ENVIRONMENT_TARGETS: EnvironmentTarget[] = [
  {
    stage: 'seed',
    tempDay: '75-80F (24-27C)',
    tempNight: '70-75F (21-24C)',
    humidity: '65-80%',
    vpd: '0.4-0.8 kPa',
    lightHours: 18,
    lightIntensity: '200-400 PPFD',
    notes: 'Gentle environment. No direct light.',
  },
  {
    stage: 'germination',
    tempDay: '75-80F (24-27C)',
    tempNight: '70-75F (21-24C)',
    humidity: '70-90%',
    vpd: '0.4-0.8 kPa',
    lightHours: 18,
    lightIntensity: '200-400 PPFD',
    notes: 'Warmth is critical. No light needed until sprout.',
  },
  {
    stage: 'seedling',
    tempDay: '72-78F (22-26C)',
    tempNight: '65-72F (18-22C)',
    humidity: '65-80%',
    vpd: '0.4-0.8 kPa',
    lightHours: 18,
    lightIntensity: '200-400 PPFD',
    notes: 'High humidity. Gentle light. Watch for damping off.',
  },
  {
    stage: 'vegetative',
    tempDay: '70-85F (21-29C)',
    tempNight: '65-75F (18-24C)',
    humidity: '40-70%',
    vpd: '0.8-1.2 kPa',
    lightHours: 18,
    lightIntensity: '400-600 PPFD',
    notes: 'Peak growth. Can handle more light and nutrients.',
  },
  {
    stage: 'pre-flower',
    tempDay: '70-82F (21-28C)',
    tempNight: '65-75F (18-24C)',
    humidity: '40-60%',
    vpd: '0.8-1.2 kPa',
    lightHours: 12,
    lightIntensity: '500-700 PPFD',
    notes: 'Transition. Switch to 12/12. Reduce humidity gradually.',
  },
  {
    stage: 'flowering',
    tempDay: '68-80F (20-27C)',
    tempNight: '65-72F (18-22C)',
    humidity: '40-55%',
    vpd: '1.0-1.4 kPa',
    lightHours: 12,
    lightIntensity: '600-900 PPFD',
    notes: 'Bud development. Keep humidity below 55% to prevent mold.',
  },
  {
    stage: 'late-flowering',
    tempDay: '65-78F (18-26C)',
    tempNight: '60-68F (15-20C)',
    humidity: '35-50%',
    vpd: '1.0-1.4 kPa',
    lightHours: 12,
    lightIntensity: '500-800 PPFD',
    notes: 'Final flush. Low humidity critical. Cool temps enhance colors.',
  },
  {
    stage: 'harvest',
    tempDay: '65-75F (18-24C)',
    tempNight: '60-68F (15-20C)',
    humidity: '45-55%',
    vpd: '0.8-1.2 kPa',
    lightHours: 12,
    lightIntensity: '200-400 PPFD',
    notes: 'Harvest in morning after dark period.',
  },
  {
    stage: 'drying',
    tempDay: '60-65F (15-18C)',
    tempNight: '58-62F (14-17C)',
    humidity: '55-65%',
    vpd: '0.6-0.8 kPa',
    lightHours: 0,
    lightIntensity: '0 PPFD',
    notes: 'Slow dry in dark. 60/60 rule. No direct light.',
  },
  {
    stage: 'curing',
    tempDay: '60-70F (15-21C)',
    tempNight: '60-70F (15-21C)',
    humidity: '58-62% (in jar)',
    vpd: 'N/A',
    lightHours: 0,
    lightIntensity: '0 PPFD',
    notes: 'Airtight jars. Burp daily first week. Store in dark.',
  },
  {
    stage: 'complete',
    tempDay: '60-70F (15-21C)',
    tempNight: '60-70F (15-21C)',
    humidity: '58-62%',
    vpd: 'N/A',
    lightHours: 0,
    lightIntensity: '0 PPFD',
    notes: 'Store cured buds in cool, dark, dry place.',
  },
];

export const NUTRIENT_SCHEDULES: NutrientSchedule[] = [
  {
    stage: 'seedling',
    week: 1,
    nutrients: [],
    phRange: '6.0-6.5 (soil) / 5.5-6.0 (hydro)',
    ecRange: '0.2-0.4',
    ppmRange: '100-200',
    notes: 'Plain water only. No nutrients needed.',
  },
  {
    stage: 'vegetative',
    week: 1,
    nutrients: [
      { type: 'grow', amount: '25-50% strength', frequency: 'every watering' },
      { type: 'calmag', amount: '1-2 ml/L', frequency: 'every watering' },
    ],
    phRange: '6.0-7.0 (soil) / 5.5-6.5 (hydro)',
    ecRange: '0.8-1.2',
    ppmRange: '400-600',
    notes: 'Start low. Increase weekly. Flush every 2 weeks.',
  },
  {
    stage: 'vegetative',
    week: 2,
    nutrients: [
      { type: 'grow', amount: '50-75% strength', frequency: 'every watering' },
      { type: 'calmag', amount: '1-2 ml/L', frequency: 'every watering' },
      { type: 'micro', amount: 'per label', frequency: 'every watering' },
    ],
    phRange: '6.0-7.0 (soil) / 5.5-6.5 (hydro)',
    ecRange: '1.0-1.4',
    ppmRange: '500-700',
    notes: 'Increase nutrients. Watch for burn tips.',
  },
  {
    stage: 'vegetative',
    week: 3,
    nutrients: [
      { type: 'grow', amount: '75-100% strength', frequency: 'every watering' },
      { type: 'calmag', amount: '2 ml/L', frequency: 'every watering' },
      { type: 'micro', amount: 'per label', frequency: 'every watering' },
      { type: 'silica', amount: 'per label', frequency: 'every watering' },
    ],
    phRange: '6.0-7.0 (soil) / 5.5-6.5 (hydro)',
    ecRange: '1.2-1.6',
    ppmRange: '600-800',
    notes: 'Full veg strength. Consider topping if 4+ nodes.',
  },
  {
    stage: 'vegetative',
    week: 4,
    nutrients: [
      { type: 'grow', amount: '100% strength', frequency: 'every watering' },
      { type: 'calmag', amount: '2 ml/L', frequency: 'every watering' },
      { type: 'micro', amount: 'per label', frequency: 'every watering' },
      { type: 'silica', amount: 'per label', frequency: 'every watering' },
    ],
    phRange: '6.0-7.0 (soil) / 5.5-6.5 (hydro)',
    ecRange: '1.2-1.8',
    ppmRange: '600-900',
    notes: 'Full strength. Apply LST. Prepare for transition.',
  },
  {
    stage: 'flowering',
    week: 1,
    nutrients: [
      { type: 'bloom', amount: '50% strength', frequency: 'every watering' },
      { type: 'calmag', amount: '2 ml/L', frequency: 'every watering' },
      { type: 'micro', amount: 'per label', frequency: 'every watering' },
    ],
    phRange: '6.0-6.8 (soil) / 5.5-6.2 (hydro)',
    ecRange: '1.2-1.6',
    ppmRange: '600-800',
    notes: 'Switch to bloom formula. Reduce nitrogen.',
  },
  {
    stage: 'flowering',
    week: 2,
    nutrients: [
      { type: 'bloom', amount: '75% strength', frequency: 'every watering' },
      { type: 'calmag', amount: '2 ml/L', frequency: 'every watering' },
      { type: 'boost', amount: 'per label', frequency: 'every watering' },
    ],
    phRange: '6.0-6.8 (soil) / 5.5-6.2 (hydro)',
    ecRange: '1.4-1.8',
    ppmRange: '700-900',
    notes: 'Buds forming. Increase bloom nutrients.',
  },
  {
    stage: 'flowering',
    week: 3,
    nutrients: [
      { type: 'bloom', amount: '100% strength', frequency: 'every watering' },
      { type: 'calmag', amount: '2 ml/L', frequency: 'every watering' },
      { type: 'boost', amount: 'per label', frequency: 'every watering' },
      { type: 'enzyme', amount: 'per label', frequency: 'weekly' },
    ],
    phRange: '6.0-6.8 (soil) / 5.5-6.2 (hydro)',
    ecRange: '1.4-2.0',
    ppmRange: '700-1000',
    notes: 'Peak feeding. Watch for burn. Defoliate for light.',
  },
  {
    stage: 'flowering',
    week: 4,
    nutrients: [
      { type: 'bloom', amount: '100% strength', frequency: 'every watering' },
      { type: 'boost', amount: 'per label', frequency: 'every watering' },
      { type: 'calmag', amount: '1 ml/L', frequency: 'every watering' },
    ],
    phRange: '6.0-6.8 (soil) / 5.5-6.2 (hydro)',
    ecRange: '1.4-1.8',
    ppmRange: '700-900',
    notes: 'Buds swelling. Maintain feeding. Reduce humidity.',
  },
  {
    stage: 'flowering',
    week: 5,
    nutrients: [
      { type: 'bloom', amount: '100% strength', frequency: 'every watering' },
      { type: 'boost', amount: 'per label', frequency: 'every watering' },
    ],
    phRange: '6.0-6.8 (soil) / 5.5-6.2 (hydro)',
    ecRange: '1.2-1.6',
    ppmRange: '600-800',
    notes: 'Begin reducing nutrients. Monitor trichomes.',
  },
  {
    stage: 'late-flowering',
    week: 1,
    nutrients: [
      { type: 'bloom', amount: '50% strength', frequency: 'every other watering' },
    ],
    phRange: '6.0-6.5 (soil)',
    ecRange: '0.6-1.0',
    ppmRange: '300-500',
    notes: 'Start flush period. Reduce nutrients significantly.',
  },
  {
    stage: 'late-flowering',
    week: 2,
    nutrients: [],
    phRange: '6.0-6.5 (soil)',
    ecRange: '0.0-0.4',
    ppmRange: '0-200',
    notes: 'Full flush with plain pH water. Final 1-2 weeks.',
  },
];

export const WATERING_GUIDELINES = {
  seedling: 'Mist spray. Water small amount around seedling. Every 2-3 days.',
  vegetative: 'Water until 10-20% runoff. Let top inch dry between waterings.',
  flowering: 'Water deeply until runoff. Every 2-3 days depending on pot size.',
  lateFlowering: 'Flush with plain water. Continue deep watering schedule.',
  general: 'Lift pot to feel weight. Water when pot feels light. Overwatering is the #1 beginner mistake.',
};

export const PH_GUIDELINES = {
  soil: { min: 6.0, max: 7.0, optimal: 6.5 },
  coco: { min: 5.5, max: 6.5, optimal: 5.8 },
  hydro: { min: 5.5, max: 6.5, optimal: 5.8 },
  notes: 'pH is the most critical factor. Incorrect pH locks out nutrients even if they are present.',
};

export const DEFOLIATION_GUIDE = {
  vegetative: 'Remove only large fan leaves blocking bud sites. Max 20% of leaves per session.',
  flowering: {
    week1: 'Light defoliation. Remove leaves blocking top bud sites.',
    week2_3: 'Moderate defoliation. Open up canopy for light penetration.',
    week4: 'Light defoliation only. Remove dead/yellowing leaves.',
    week5_plus: 'Minimal defoliation. Only remove dying or damaged leaves.',
  },
  notes: 'Never remove more than 30% of leaves at once. Allow 3-5 days recovery between sessions.',
};

export const TRAINING_GUIDES = {
  lst: {
    name: 'Low Stress Training',
    description: 'Bend and tie down branches to create an even canopy.',
    whenToStart: 'Week 2-3 of veg when plant has 4-6 nodes',
    howTo: [
      'Use soft plant wire or pipe cleaners',
      'Gently bend main stem sideways',
      'Tie to pot edge or training wire',
      'Redirect growth tips upward',
      'Reposition ties as plant grows',
    ],
    benefits: ['Even canopy', 'More bud sites', 'Better light penetration', 'Controlled height'],
  },
  topping: {
    name: 'Topping',
    description: 'Cut the main growth tip to create two main colas.',
    whenToStart: 'When plant has 4-6 nodes (week 3-4)',
    howTo: [
      'Use clean, sharp scissors',
      'Cut above the 3rd or 4th node',
      'Remove the entire growth tip',
      'Plant will produce two new main stems',
      'Can top again for 4 colas',
    ],
    benefits: ['More main colas', 'Bushier plant', 'Better yield distribution'],
  },
  scrog: {
    name: 'Screen of Green (SCROG)',
    description: 'Weave branches through a horizontal screen for even canopy.',
    whenToStart: 'Set up screen at week 2-3 of veg',
    howTo: [
      'Install horizontal net/screen 12-18 inches above pot',
      'Weave growing branches through screen squares',
      'Tuck branches under screen to redirect growth',
      'Fill entire screen before switching to flower',
      'Remove any growth below the screen',
    ],
    benefits: ['Maximum light exposure', 'Even canopy', 'High yield per square foot'],
  },
  supercropping: {
    name: 'Supercropping (HST)',
    description: 'High stress technique - bend branches until inner stem cracks.',
    whenToStart: 'Week 3-4 of veg',
    howTo: [
      'Choose a branch to bend',
      'Squeeze stem firmly between fingers',
      'Bend branch to 90 degrees',
      'Support bent branch until healed',
      'Creates a knuckle that strengthens the branch',
    ],
    benefits: ['Stronger branches', 'More cola sites', 'Controls height'],
  },
};

export const COMMON_DEFICIENCIES = {
  nitrogen: { symptoms: 'Yellowing of lower leaves, starting from tips inward', fix: 'Increase nitrogen (grow nutrients)' },
  phosphorus: { symptoms: 'Dark green leaves with purple/red undersides', fix: 'Increase phosphorus (bloom nutrients)' },
  potassium: { symptoms: 'Yellow/brown leaf edges, curling tips', fix: 'Increase potassium' },
  calcium: { symptoms: 'New growth distorted, spotted leaves', fix: 'Add Cal-Mag supplement' },
  magnesium: { symptoms: 'Interveinal chlorosis on older leaves', fix: 'Add Cal-Mag or Epsom salt (1 tsp/gal)' },
  iron: { symptoms: 'Yellowing of new leaves while veins stay green', fix: 'Check pH, add iron supplement' },
  sulfur: { symptoms: 'Pale new growth, similar to nitrogen deficiency', fix: 'Add sulfur supplement' },
  manganese: { symptoms: 'Interveinal chlorosis on younger leaves', fix: 'Check pH, add manganese' },
  zinc: { symptoms: 'Small leaves, interveinal chlorosis, stunted growth', fix: 'Check pH, add zinc supplement' },
  boron: { symptoms: 'Growing tips die back, hollow stems', fix: 'Add boron supplement' },
};

export const PEST_GUIDE = {
  spiderMites: {
    name: 'Spider Mites',
    signs: 'Tiny dots on leaves, fine webbing, stippled leaves',
    prevention: 'Keep humidity above 45%, maintain airflow, neem oil prevention',
    treatment: 'Neem oil spray, ladybugs, predatory mites, insecticidal soap',
  },
  fungusGnats: {
    name: 'Fungus Gnats',
    signs: 'Small flying insects around soil, larvae in top layer',
    prevention: 'Let soil dry between waterings, use sticky traps',
    treatment: 'Mosquito bits in water, yellow sticky traps, diatomaceous earth on soil',
  },
  aphids: {
    name: 'Aphids',
    signs: 'Clusters of small insects on stems and undersides of leaves',
    prevention: 'Companion planting, neem oil',
    treatment: 'Strong water spray, neem oil, insecticidal soap, ladybugs',
  },
  thrips: {
    name: 'Thrips',
    signs: 'Silver/bronze streaks on leaves, tiny larvae',
    prevention: 'Keep area clean, use sticky traps',
    treatment: 'Neem oil, spinosad, predatory insects',
  },
  whiteflies: {
    name: 'Whiteflies',
    signs: 'Small white flying insects, sticky honeydew on leaves',
    prevention: 'Yellow sticky traps, companion planting',
    treatment: 'Neem oil, insecticidal soap, reflective mulch',
  },
  caterpillars: {
    name: 'Caterpillars',
    signs: 'Chewed leaves, droppings (frass)',
    prevention: 'Hand picking, row covers',
    treatment: 'Bt (Bacillus thuringiensis), hand removal',
  },
  powderyMildew: {
    name: 'Powdery Mildew',
    signs: 'White powdery spots on leaves',
    prevention: 'Good airflow, moderate humidity, baking soda spray',
    treatment: 'Milk spray (40:60 milk:water), neem oil, potassium bicarbonate',
  },
  budRot: {
    name: 'Bud Rot (Botrytis)',
    signs: 'Gray mold inside buds, buds turning brown/mushy',
    prevention: 'Keep humidity below 55% in flower, good airflow',
    treatment: 'Remove affected buds immediately, improve conditions',
  },
};

export const HARVEST_TIMING_GUIDE = {
  early: {
    trichomes: 'Mostly clear',
    pistils: '10-30% turned',
    effect: 'Energetic, cerebral, uplifting',
    description: 'Harvested before peak ripeness. More energetic effects.',
  },
  optimal: {
    trichomes: 'Mostly cloudy with some amber',
    pistils: '50-70% turned',
    effect: 'Balanced, potent, full spectrum',
    description: 'Ideal harvest window for balanced effects.',
  },
  late: {
    trichomes: 'Mostly amber with some cloudy',
    pistils: '70-90% turned',
    effect: 'Relaxing, body-heavy, sedating',
    description: 'Late harvest for more couch-lock effects.',
  },
};

export const STRAINS_INFO = {
  photoperiod: {
    description: 'Requires 12/12 light cycle to flower',
    advantages: ['More control', 'Larger yields', 'Can clone', 'Longer veg time'],
    disadvantages: ['Longer grow time', 'Light schedule sensitive', 'Hermaphrodite risk'],
  },
  autoflower: {
    description: 'Flowers automatically based on age, not light cycle',
    advantages: ['Faster to harvest', 'Light schedule flexible', 'Easier for beginners', 'Can harvest multiple per season'],
    disadvantages: ['Smaller yields', 'Cannot clone', 'Less training time', 'Less control over size'],
  },
};
