export const CANNABIS_FACTS = [
  "Cannabis has been used for at least 5,000 years, with early evidence found in China and Central Asia.",
  "The word 'marijuana' comes from the Mexican Spanish word 'marihuana.'",
  "Cannabis contains over 100 different cannabinoids, including THC and CBD.",
  "Hemp was so important in colonial America that farmers were legally required to grow it.",
  "The strongest natural strain of cannabis can contain over 30% THC.",
  "Cannabis was legal in most of the world until the early 20th century.",
  "The human body has an endocannabinoid system that naturally interacts with cannabis compounds.",
  "Women produce more cannabinoids than men, according to some research.",
  "Cannabis can help reduce nausea, pain, and inflammation.",
  "The oldest known cannabis smoke was found in 2,500-year-old tombs in China.",
  "Some strains of cannabis can produce over 100 different terpenes.",
  "Cannabis was used as currency in ancient India.",
  "George Washington grew hemp at Mount Vernon.",
  "Cannabis seeds are one of the most nutritious seeds on Earth.",
  "The largest joint ever smoked contained 360 grams of cannabis.",
  "Cannabis can grow in almost any climate on Earth.",
  "The word 'bhang' refers to a traditional Indian cannabis drink.",
  "Some studies suggest cannabis may help with PTSD symptoms.",
  "Cannabis plants can be male, female, or hermaphrodite.",
  "The fastest growing plant on Earth is cannabis, capable of growing 2 inches per day.",
  "Cannabis was used in religious ceremonies by ancient Scythians.",
  "CBD was first discovered in 1940, but THC wasn't isolated until 1964.",
  "Cannabis can be used to make over 25,000 different products.",
  "The largest legal cannabis plant was 65 feet tall.",
  "Cannabis legalization has generated billions in tax revenue in legal states.",
  "The smell of cannabis comes from terpenes, not cannabinoids.",
  "Some people are genetically more sensitive to cannabis than others.",
  "Cannabis can remain potent for years if stored properly.",
  "The first recorded use of cannabis for medical purposes was in 2737 BC in China.",
  "Cannabis plants can communicate with each other through chemical signals.",
  "The average joint contains about 0.5 grams of cannabis.",
  "Cannabis was used to treat migraines as far back as 700 AD.",
  "Some strains of cannabis produce a lemon scent due to high limonene content.",
  "Cannabis can help increase appetite in chemotherapy patients.",
  "The cannabis industry is one of the fastest-growing industries in the world.",
  "Cannabis plants have been found growing on every continent except Antarctica.",
  "The oldest cannabis seed found was in a 2,700-year-old grave in Romania.",
  "Cannabis can help reduce muscle spasms in multiple sclerosis patients.",
  "Some people experience synesthesia when using cannabis.",
  "The endocannabinoid system was discovered in the 1990s.",
  "Cannabis can be used to make paper, clothing, and building materials.",
  "The word 'sinsemilla' means 'without seed' in Spanish.",
  "Cannabis can help with sleep disorders in some patients.",
  "The first cannabis dispensary in the US opened in 1996 in San Francisco.",
  "Cannabis plants can produce different effects depending on their terpene profile.",
  "Some indigenous cultures used cannabis in shamanic rituals.",
  "Cannabis can help reduce anxiety in some people but increase it in others.",
  "The largest cannabis garden in the world covers over 4 acres.",
  "Cannabis has been used to treat epilepsy for centuries.",
  "The first recorded use of cannabis smoking was in China around 500 BC.",
  "Snoop Dogg once claimed to have smoked 81 blunts a day back in his prime.",
  "Cheech and Chong's Up in Smoke (1978) became a cult classic and grossed over $100 million worldwide.",
  "Snoop Dogg launched his own cannabis brand called 'Leafs by Snoop' in 2015.",
  "Wiz Khalifa has his own cannabis strain called 'Khalifa Kush.'",
  "Seth Rogen co-founded a cannabis company called Houseplant and is a known grower himself.",
  "Bob Marley was one of the most iconic cannabis advocates in history and even has a strain named after him.",
  " Willie Nelson has his own cannabis brand called 'Willie's Reserve.'",
  "Snoop Dogg and Martha Stewart became unlikely best friends over their shared love of good vibes.",
  "Cheech Marin and Tommy Chong met in a comedy club in Calgary in 1969 and the rest is history.",
  "Redman and Method Man were so known for smoking that they hosted a weed-themed cooking show.",
  "B-Real of Cypress Hill popularized the high-pitched rap style and is a major cannabis entrepreneur.",
  "Bernie Sanders won the 'Grassdoor' cannabis election poll in 2020.",
  "Wiz Khalifa appeared on Conan and rolled a joint live on camera in 2015.",
  "Snoop Dogg once narrated a nature documentary about cannabis for Viceland.",
  "Seth Rogen grew his own cannabis garden during quarantine and posted it on Instagram.",
  "Mary Jane is a slang term for marijuana that originated in the 1920s.",
  "Snoop Dogg has a joint roller on staff whose official job title is 'Pimp Cup Holder.'",
  "Waka Flocka Flame ran for president in 2016 on a platform that included legalizing weed.",
  "Rapper Killer Mike opened a cannabis dispensary in Atlanta to benefit Black communities.",
  "The Grateful Dead were famous for spawning the 'Deadhead' culture that embraced cannabis.",
  "Harold and Kumar Go to White Castle (2004) became a stoner comedy classic.",
  "Dr. Dre's 'The Chronic' album is named after a cannabis strain and helped define West Coast hip-hop.",
  "Mike Tyson has a 40-acre cannabis ranch in California and grows his own strains.",
  "Weedmaps is the largest cannabis delivery marketplace, founded in 2008.",
  "Snoop Dogg smoked with Martha Stewart on her show and called it one of his proudest moments.",
  "The cannabis industry in the US was worth over $30 billion in 2023.",
  "Cheech and Chong's NEXT movie was fully funded through crowdfunding from fans.",
  "Rihanna has been open about her cannabis use and even smoked on camera at the Met Gala.",
  "Travis Barker and Machine Gun Kelly launched a cannabis brand together called 'UN/DN LAQR.'",
  "Snoop Dogg has his own cereal called 'Snoop Loopz' with cannabis leaf-shaped marshmallows.",
  "Harold Ramis and Seth Rogen both directed cannabis-themed movies that became cult classics.",
  "Seth Rogen's character in Pineapple Express helped popularize the concept of a 'cannabis enthusiast' in mainstream comedy.",
  "Bob Marley's daughter Cedella launched a cannabis brand called 'Marley Natural.'",
  "The first weed-friendly bed and breakfast opened in Colorado in 2014.",
  "Snoop Dogg was the first celebrity to launch a cannabis brand on the Canadian Stock Exchange.",
  "Willie Nelson was arrested for weed in 1978 and said 'I never smoke nothin' that don't got seeds in it.'",
  "Wiz Khalifa's 'See You Again' music video was filmed after he smoked and came up with the idea.",
  "Cheech and Chong's 'Dave' character became one of the most iconic stoner personas in film history.",
];

export function getRandomFact(): string {
  const index = Math.floor(Math.random() * CANNABIS_FACTS.length);
  return CANNABIS_FACTS[index];
}
